### ISSUE TITLE
Not working with Colyseus proxy

### ISSUE THREAD

**Issue by CookedApps** [colyseus/uWebSockets-express#17]
I am not sure if this is the right repo for reporting this. Sorry if it's not. :smile: 

### Setup
- Colyseus proxy running on Kubernetes
- Game servers using uWebSockets transport layer

### Problem
- Game servers stopped registering themselves to the Colyseus proxy after switchting to uWebSockets transport
- Requests to the proxy end up with error `503` and proxy prints out `No proxy available! {}`. 
- `remove` event gets fired from the game servers when shutting one down. (Proxy loggs the event.)
→ Seemingly they are able to communicate with the Redis presence.

The proxy was working fine before switching to the new transport layer.

Thanks in advance! :pray:

**Comment by endel** [comment]
Hi @CookedApps, I belive this has been fixed in a patch version of `@colyseus/core` along with `@colyseus/uwebsockets-transport`, can you please confirm which version of which are you using? Cheers

**Comment by CookedApps** [comment]
@endel Sure! We are currently using: 
- `@colyseus/core` - 0.14.28
- `@colyseus/uwebsockets-transport` - 0.14.28
- `uwebsockets-express` - 1.2.2

I fear these are the newest versions, though. :smile:

**Comment by endel** [comment]
Hey @CookedApps, this had already been fixed on upcoming `0.15` (https://github.com/colyseus/colyseus/pull/464).

I've just cherry-picked the relevant commits and pushed on the current `0.14`, can you please check if that works for you now?

- `@colyseus/core@0.14.29`
- `@colyseus/uwebsockets-transport@0.14.29`

**Comment by CookedApps** [comment]
You, @endel, are a man of honor. It works! Thank you so much for the patch! :clap:
