### ISSUE TITLE
Could not find a declaration file for module 'uwebsockets-express'.

### ISSUE THREAD

**Issue by Byloth** [colyseus/uWebSockets-express#36]
I'm experiencing this error after upgrading to the latest version `1.3.9`:

```log
src/core.ts:8:24 - error TS7016: Could not find a declaration file for module 'uwebsockets-express'. '/home/matteo/colyseus-example/node_modules/uwebsockets-express/build/index.mjs' implicitly has an 'any' type.
  There are types at '/home/matteo/colyseus-example/node_modules/uwebsockets-express/build/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'uwebsockets-express' library may need to update its package.json or typings.

8 import expressify from "uwebsockets-express";
                         ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by endel** [comment]
Hi @Byloth, sorry and thanks for letting me know - please stick with version `1.3.6` for now 🙏 

I'm updating how to build this project in order to support ESM and it seems build is bad on versions higher than `1.3.6`.

**Comment by Byloth** [comment]
Sure, no problem... I noticed it!  
Don't worry... I've already rolled back to the previous version.

This was just to let you know! 😉

**Comment by endel** [comment]
Thank you for raising this issue so fast, I believe this got fixed on https://github.com/colyseus/uWebSockets-express/commit/a78e8d2b0c8ce56866a063e9788002f728826772 🙏
