### ISSUE TITLE
Express router middleware/route order issue

### ISSUE THREAD

**Issue by ryanwillis** [colyseus/uWebSockets-express#8]
Hi there, thanks for the great package!

I noticed that when passing an express router to `use`, the order of middleware and routes are not preserved. Middleware are always executed before routes even when defined afterwards.

**To Reproduce:**
Hit reload in the browser pane of each of these examples and check the console.

uWebSockets-express middleware order: https://codesandbox.io/s/uwebsockets-express-middleware-order-issue-jcw6z

Express router middleware order: https://codesandbox.io/s/express-router-as-middleware-ordering-7rxgv

**Comment by endel** [comment]
Thanks for the reproduction scenario! Gonna take a look soon!

**Comment by ryanwillis** [comment]
Any luck with this?
